name: CI/CD Pipeline

on:
  release:
    types:
      - created
  workflow_dispatch:
    inputs:
      environment:
        description: 'production environment'
        required: true
        default: 'production'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    # Step 1: Check out the code
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Setup .NET environment
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 5.0

    # Step 3: Restore dependencies
    - name: Restore Dependencies
      run: dotnet restore DevOpsChallenge.SalesApi.sln

    # Step 4: Build the solution
    - name: Build Solution
      run: dotnet build DevOpsChallenge.SalesApi.sln --configuration Release

    # Step 5: Running the API in the background for Unit Testing
    - name: Start API Server
      run: nohup dotnet run --project src/DevOpsChallenge.SalesApi/DevOpsChallenge.SalesApi.csproj &

    # Step 6: Run Unit Tests
    - name: Run Unit Tests
      run: dotnet test DevOpsChallenge.SalesApi.sln --configuration Release

    # Step 7: Build Docker image
    - name: Build Docker Image
      run: |
        docker build -t shithush/sales-api:latest .

    # Step 8: Push Docker image to Docker Hub
    - name: Push Docker Image
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        docker push shithush/sales-api:latest
